### ISSUE TITLE
Declare a minimum supported Rust version (v0.9.0 fails to build on rustc 1.92 with E0658)

### ISSUE THREAD

**Issue by ooo27** [EpicGames/lore#199]
### Lore version

v0.9.0 tag (built from source)

### Installation method

Built from source

### Operating system / architecture

Linux (Ubuntu 22.04, WSL2) / x86_64

### Steps to reproduce

With rustc 1.92.0 (stable from December 2025) installed:

```
git clone --branch v0.9.0 https://github.com/EpicGames/lore
cd lore
cargo build --release -p lore-client
```

### Expected vs actual behavior

Expected: either a successful build, or an immediate "package requires rustc X or newer" from cargo.

Actual: most of the ~550 dependencies compile (several minutes), then:

```
error[E0658]: use of unstable library feature `maybe_uninit_slice`
   --> lore-storage/src/hash.rs:127:78
    |
127 |             return xxhash_rust::xxh3::xxh3_64(unsafe { buffer[..bytes.len()].assume_init_ref() });
    |                                                                              ^^^^^^^^^^^^^^^
error: could not compile `lore-storage` (lib) due to 1 previous error
```

E0658 does not say which Rust version is needed. The build succeeds on rustc 1.98.1.

The root cause is that the repository does not declare a minimum supported Rust version: there is no `rust-toolchain.toml`, no `rust-version` in the workspace `Cargo.toml`, and CONTRIBUTING.md and docs/how-to/install-lore-cli.md only say "the stable toolchain". In practice that means "the latest stable", which is not obvious to someone on an LTS box.

This matters more than usual because building from source is currently the only way to run the CLI on Ubuntu 22.04 (the prebuilt Linux binaries require GLIBC 2.39, see #143), and those users are the most likely to have an older toolchain.

Suggestion, any one of:

- Add `rust-version` under `[workspace.package]` so cargo fails fast with a clear message.
- Add a `rust-toolchain.toml` so rustup selects the right toolchain automatically.
- State the minimum version in the install and contributing docs.

A `cargo +<msrv> check` step in CI would keep whichever one is chosen honest.

### Component

Build / repository tooling (lore-storage is where it surfaces)
